#spring.thymeleaf.enabled=true
#spring.thymeleaf.prefix=/resources/templates/

spring:
    profiles: 
        active: ${ENV:localhost}
        include: validation
    application:
        name: "thymeleaf-poc"

server:
    servlet:
        context-path: "/api/thymeleaf-poc/v1"
    error:
        include-message: always
open:
  api:
    spec:
      url: myspec.yml
      
product:
  name: WORK
  pet:
    url: /api/thymeleaf-poc/v1/pet